BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Application CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Vacancy CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Company CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE Resume CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE "User" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "User" (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email NVARCHAR2(255) NOT NULL, 
    Password RAW(2000) NOT NULL, 
    Role NUMBER(1) CHECK (Role BETWEEN 1 AND 3), 
    Phone NVARCHAR2(20) NOT NULL,
    Is_active NUMBER(1) DEFAULT 1 CHECK (Is_active IN (0, 1))
);

CREATE TABLE Resume (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_id INT REFERENCES "User"(ID), 
    Desired_Position NVARCHAR2(255),
    Salary_Expectation NUMBER(18, 2), 
    Skills CLOB, 
    Work_Experience CLOB,
    City NVARCHAR2(100)
);

CREATE TABLE Company (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Owner_id INT REFERENCES "User"(ID),
    Title NVARCHAR2(255) NOT NULL,
    Description CLOB NOT NULL,
    Address CLOB NOT NULL
);

CREATE TABLE Vacancy (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Company_id INT REFERENCES Company(ID),
    Job_title NVARCHAR2(255) NOT NULL,
    Requirement CLOB NOT NULL,
    Salary_range NVARCHAR2(100),
    Publication_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    Is_active NUMBER(1) DEFAULT 1 CHECK (Is_active IN (0, 1))
);

CREATE TABLE Application (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    vacancy_id INT REFERENCES Vacancy(ID),
    resume_id INT REFERENCES Resume(ID),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status NVARCHAR2(50) CHECK (status IN ('new','approved','rejected','in consideration'))
);

BEGIN
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('admin@global.com', HEXTORAW('ABC123AF'), 1, '+12025550100', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('dmitry.dev@gmail.com', HEXTORAW('1111'), 2, '+442079460123', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('elena.hr@itechart.com', HEXTORAW('2222'), 3, '+375292223344', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('vlad.fullstack@yahoo.com', HEXTORAW('3333'), 2, '+375293334455', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('olga.recruiter@epam.com', HEXTORAW('4444'), 3, '+375294445566', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('ivan.eng@outlook.com', HEXTORAW('5555'), 2, '+375295556677', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('ceo@heavytech.com', HEXTORAW('6666'), 3, '+375172221122', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('kate.marketing@proton.me', HEXTORAW('7777'), 2, '+375297778899', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('hr@retailgiant.com', HEXTORAW('8888'), 3, '+375441112233', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('alex.qa@icloud.com', HEXTORAW('9999'), 2, '+375259998877', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('talent@telecom.by', HEXTORAW('0000'), 3, '+375173334455', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('maxim.sys@gmail.com', HEXTORAW('AAAA'), 2, '+375291234567', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('hr@brewery.com', HEXTORAW('BBBB'), 3, '+375297654321', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('sveta.fin@tut.by', HEXTORAW('CCCC'), 2, '+375336001122', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('hiring@bankgroup.com', HEXTORAW('DDDD'), 3, '+375179998877', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('pavel.design@behance.net', HEXTORAW('EEEE'), 2, '+375298887766', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('hr@tractorfactory.com', HEXTORAW('FFFF'), 3, '+375174445566', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('anna.sales@salesforce.com', HEXTORAW('1212'), 2, '+375292220011', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('recruitment@wargaming.net', HEXTORAW('3232'), 3, '+375175556677', 1);
  INSERT INTO "User" (Email, Password, Role, Phone, Is_active) VALUES ('igor.devops@linux.com', HEXTORAW('4242'), 2, '+375257008090', 1);

  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (3, N'iTechArt Group', N'Software development.', N'8 Tolstogo St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (5, N'EPAM Systems', N'Digital services.', N'1/1 Kuprevicha St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (7, N'HeavyTech MAZ', N'Truck manufacturer.', N'2 Sotsialisticheskaya St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (9, N'Retail Network Inc', N'Grocery chain.', N'2 Montazhnikov St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (11, N'National Telecom', N'ISP provider.', N'6 Engelsa St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (13, N'Liberty Brewery', N'Brewing company.', N'30 Kiseleva St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (15, N'Global Bank OAO', N'Banking services.', N'38A Radialnaya St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (17, N'AgroMach Factory', N'Machinery.', N'29 Dolgobrodskaya St, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (19, N'Wargaming', N'Game developer.', N'178 Partizanskiy Ave, Minsk');
  INSERT INTO Company (Owner_id, Title, Description, Address) VALUES (5, N'LeverX Group', N'SAP Partner.', N'51 Klary Tsetkin St, Minsk');

  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (2, N'Senior .NET Developer', 8500, N'C#, SQL', N'8 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (4, N'Fullstack JS Developer', 5000, N'Node, React', N'3 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (6, N'Mechanical Engineer', 2200, N'AutoCAD', N'10 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (8, N'Digital Marketer', 2800, N'SEO, Ads', N'4 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (10, N'QA Engineer', 1800, N'Jira, Manual', N'1 year', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (12, N'Sys Admin', 3000, N'Linux, Docker', N'6 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (14, N'Accountant', 3500, N'SAP, Tax', N'12 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (16, N'Designer', 4200, N'Figma', N'5 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (18, N'Sales Manager', 2000, N'B2B', N'2 years', N'Minsk');
  INSERT INTO Resume (User_id, Desired_Position, Salary_Expectation, Skills, Work_Experience, City) VALUES (20, N'DevOps Engineer', 7000, N'K8s, AWS', N'4 years', N'Minsk');

  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (1, N'.NET Dev', N'C# skills', N'4k-7k', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (2, N'Java Eng', N'Senior level', N'9k+', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (3, N'Mechanic', N'Experience', N'2k', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (4, N'Cashier', N'Service', N'1.5k', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (5, N'Network Eng', N'CCNA', N'2k', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (6, N'Technologist', N'Food exp', N'3k', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (7, N'Loan Spec', N'Banking', N'3k', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (8, N'Machinist', N'5th cat', N'3k', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (9, N'Designer', N'Game exp', N'Negot.', SYSTIMESTAMP, 1);
  INSERT INTO Vacancy (Company_id, Job_title, Requirement, Salary_range, Publication_date, Is_active) VALUES (10, N'SAP Cons', N'ABAP', N'5k+', SYSTIMESTAMP, 1);

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 1, SYSTIMESTAMP, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 1, SYSTIMESTAMP, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 10, SYSTIMESTAMP, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 8, SYSTIMESTAMP, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 9, SYSTIMESTAMP, 'rejected');
  
  COMMIT;
END;
/



BEGIN
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 1, SYSDATE - 360, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 2, SYSDATE - 355, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 3, SYSDATE - 350, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 4, SYSDATE - 345, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 5, SYSDATE - 342, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 6, SYSDATE - 330, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 7, SYSDATE - 325, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 8, SYSDATE - 320, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 9, SYSDATE - 315, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 10, SYSDATE - 305, 'approved');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 2, SYSDATE - 295, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 3, SYSDATE - 290, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 4, SYSDATE - 285, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 5, SYSDATE - 280, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 6, SYSDATE - 275, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 7, SYSDATE - 270, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 8, SYSDATE - 265, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 9, SYSDATE - 260, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 10, SYSDATE - 255, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 1, SYSDATE - 252, 'rejected');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 3, SYSDATE - 245, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 4, SYSDATE - 240, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 5, SYSDATE - 235, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 6, SYSDATE - 230, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 7, SYSDATE - 225, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 8, SYSDATE - 220, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 9, SYSDATE - 215, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 10, SYSDATE - 210, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 1, SYSDATE - 205, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 2, SYSDATE - 200, 'approved');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 4, SYSDATE - 195, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 5, SYSDATE - 190, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 6, SYSDATE - 185, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 7, SYSDATE - 180, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 8, SYSDATE - 175, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 9, SYSDATE - 170, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 10, SYSDATE - 165, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 1, SYSDATE - 160, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 2, SYSDATE - 155, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 3, SYSDATE - 150, 'rejected');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 5, SYSDATE - 145, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 6, SYSDATE - 140, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 7, SYSDATE - 135, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 8, SYSDATE - 130, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 9, SYSDATE - 125, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 10, SYSDATE - 120, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 1, SYSDATE - 115, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 2, SYSDATE - 110, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 3, SYSDATE - 105, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 4, SYSDATE - 100, 'approved');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 6, SYSDATE - 95, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 7, SYSDATE - 90, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 8, SYSDATE - 85, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 9, SYSDATE - 80, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 10, SYSDATE - 75, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 1, SYSDATE - 70, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 2, SYSDATE - 68, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 3, SYSDATE - 65, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 4, SYSDATE - 62, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 5, SYSDATE - 60, 'in consideration');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 7, SYSDATE - 58, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 8, SYSDATE - 55, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 9, SYSDATE - 52, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 10, SYSDATE - 50, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 1, SYSDATE - 48, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 2, SYSDATE - 45, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 3, SYSDATE - 42, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 4, SYSDATE - 40, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 5, SYSDATE - 38, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 6, SYSDATE - 35, 'in consideration');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 8, SYSDATE - 30, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 9, SYSDATE - 28, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 10, SYSDATE - 26, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 1, SYSDATE - 25, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 2, SYSDATE - 22, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 3, SYSDATE - 20, 'approved');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 4, SYSDATE - 19, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 5, SYSDATE - 18, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 6, SYSDATE - 16, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 7, SYSDATE - 15, 'new');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 9, SYSDATE - 14, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 10, SYSDATE - 13, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 1, SYSDATE - 12, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 2, SYSDATE - 11, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 3, SYSDATE - 10, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 4, SYSDATE - 9, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 5, SYSDATE - 8, 'rejected');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 6, SYSDATE - 7, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 7, SYSDATE - 7, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 8, SYSDATE - 7, 'new');

  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (1, 10, SYSDATE - 6, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (2, 1, SYSDATE - 5, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (3, 2, SYSDATE - 4, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (4, 3, SYSDATE - 4, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (5, 4, SYSDATE - 3, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (6, 5, SYSDATE - 2, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (7, 6, SYSDATE - 2, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (8, 7, SYSDATE - 1, 'in consideration');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (9, 8, SYSDATE, 'new');
  INSERT INTO Application (vacancy_id, resume_id, date_created, status) VALUES (10, 9, SYSDATE, 'new');

  COMMIT;
END;
/

select * from application;