
CREATE TABLE "User" (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email NVARCHAR2(255) NOT NULL, 
    Password RAW(2000) NOT NULL, 
    Role NUMBER(1) CHECK (Role BETWEEN 1 AND 3), 
    Phone NVARCHAR2(20) NOT NULL,
    Is_active NUMBER(1) DEFAULT 1 CHECK (Is_active IN (0, 1))
);

CREATE TABLE Resume (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_id INT REFERENCES "User"(ID), 
    Desired_Position NVARCHAR2(255),
    Salary_Expectation NUMBER(18, 2), 
    Skills CLOB, 
    Work_Experience CLOB,
    City NVARCHAR2(100)
);

CREATE TABLE Company (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Owner_id INT REFERENCES "User"(ID),
    Title NVARCHAR2(255) NOT NULL,
    Description CLOB NOT NULL,
    Address CLOB NOT NULL
);

CREATE TABLE Vacancy (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Company_id INT REFERENCES Company(ID),
    Job_title NVARCHAR2(255) NOT NULL,
    Requirement CLOB NOT NULL,
    Salary_range NVARCHAR2(100),
    Publication_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    Is_active NUMBER(1) DEFAULT 1 CHECK (Is_active IN (0, 1))
);

CREATE TABLE Application (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    vacancy_id INT REFERENCES Vacancy(ID),
    resume_id INT REFERENCES Resume(ID),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status NVARCHAR2(50) CHECK (status IN ('new','approved','rejected','in consideration'))
);