services:
  database:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - "1521:1521"
    volumes:
      - C:\labi\6sem\ПРБДИП\lab10\folder_for_lob:/opt/oracle/docs
      - oracle_data:/opt/oracle/oradata