user  nginx;
worker_processes  auto;
events { 
    worker_connections  1024; 
}

stream {
    upstream mssql_backend {
        server mssql:1433; 
    }
    server {
        listen 1433;
        proxy_pass mssql_backend;
    }
}